[[redirects]]
  from = "lobvr.com"
  to = "www.lobvr.com"

[[redirects]]
  from = "/impressum"
  to = "/impressum"
  status = 304

[[redirects]]
  from = "/datenschutz"
  to = "/datenschutz"
  status = 304